# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2e4bf37a08f26217c7f1990ce9de5af0e77a0a7df26f9adcae68b4ad49407cd1d4138065192c360af6bb5b3e28a98dc3cf67010fcbd448aad26926c85a0ded

test:
  secret_key_base: 76d0a8a78cc35d492490c349fd04443b1b327bf354c29dad5ce81574b3cf2465a275baa030ab8d862b6b24cd740362ad39d5c452660431b582d740352b1a951b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
